---
  
- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install php support
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
    
  - name: update repo index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2
    yum:
      name: apache2
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install php support
    yum:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "CentOS"
